# Generated by Django 5.0.4 on 2024-05-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
