# Generated by Django 5.0.4 on 2024-05-26 23:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientsApp', '0002_pet_url_img'),
        ('employeesApp', '0002_employee_image_url'),
        ('servicesApp', '0002_service_required_speciality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('taken', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('combo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicesApp.combo')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeesApp.employee')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientsApp.pet')),
                ('services', models.ManyToManyField(related_name='appointments', to='servicesApp.service')),
                ('taken_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientsApp.client')),
            ],
        ),
    ]
