# Generated by Django 5.0.4 on 2024-05-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='url_img',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
